// EMPOWERING ENGINEERS UK - DYNAMIC FOOTER & DATA MANAGER
// INJECTS: Standard Footer + Feedback Script + Data Portability Tools

(function() {
    // 1. Calculate Current Year
    const year = new Date().getFullYear();

    // 2. Data Management Logic (Export/Import)
    window.eeDataManager = {
        exportData: function() {
            const data = JSON.stringify(localStorage);
            const blob = new Blob([data], {type: "application/json"});
            const url = URL.createObjectURL(blob);
            
            // Generate Timestamp: YYYY-MM-DD_HH-MM-SS
            // Note: We replace colons with hyphens to ensure Windows compatibility
            const now = new Date();
            const timestamp = now.toISOString().replace(/T/, '_').replace(/:/g, '-').slice(0, 19);

            const a = document.createElement('a');
            a.href = url;
            a.download = `EmpoweringEngineers_Backup_${timestamp}.json`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
        },

        triggerImport: function() {
            document.getElementById('ee-import-input').click();
        },

        handleImport: function(input) {
            const file = input.files[0];
            if (!file) return;

            const reader = new FileReader();
            reader.onload = function(e) {
                try {
                    const data = JSON.parse(e.target.result);
                    
                    if (confirm("⚠️ RESTORE WARNING:\n\nThis will overwrite your current browser data (STAR drafts, CPD logs, etc.) with the data from the backup file.\n\nAre you sure you want to proceed?")) {
                        // Clear current state to prevent conflicts
                        localStorage.clear();
                        
                        // Restore keys
                        Object.keys(data).forEach(function (k) {
                            localStorage.setItem(k, data[k]);
                        });

                        alert("✅ Data Restored Successfully.\nThe page will now reload.");
                        location.reload();
                    }
                } catch (err) {
                    alert("❌ Error: Invalid Backup File.\nPlease ensure you are uploading a valid JSON file generated by this website.");
                    console.error(err);
                }
            };
            reader.readAsText(file);
        }
    };

    // 3. Build Footer HTML (Includes Data Manager UI)
    const footerHTML = `
    <style>
        .footer-data-tools {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px dashed var(--border-color);
            font-family: 'Courier Prime', monospace;
            font-size: 0.8rem;
        }
        .data-btn {
            background: transparent;
            border: 1px solid var(--slate-grey);
            color: var(--slate-grey);
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 4px;
            margin: 0 5px;
            font-family: inherit;
            transition: all 0.2s;
        }
        .data-btn:hover {
            border-color: var(--terminal-green);
            color: var(--terminal-green);
            background: rgba(0, 255, 153, 0.05);
        }
    </style>

    <footer>
        <p>&copy; ${year} Empowering Engineers UK. All rights reserved.</p>
        <p>
            <a href="about.html">About Us</a> | 
            <a href="contact.html">Contact Us</a> | 
            <a href="terms.html">Terms of Use</a> | 
            <a href="privacy.html">Privacy Policy</a>
        </p>

        <div class="footer-data-tools">
            <span style="color:var(--burnt-orange)">[ DATA CONTROL ]</span><br>
            <span style="font-size:0.75rem; color:var(--slate-grey); display:block; margin-bottom:10px;">
                Your data is stored locally. Backup your progress or transfer to another device.
            </span>
            <button class="data-btn" onclick="window.eeDataManager.exportData()">&#11015; Save Backup</button>
            <button class="data-btn" onclick="window.eeDataManager.triggerImport()">&#11014; Restore Data</button>
            
            <input type="file" id="ee-import-input" style="display:none" accept=".json" onchange="window.eeDataManager.handleImport(this)">
        </div>
    </footer>
    `;

    // 4. Inject Footer at the bottom of the body
    document.body.insertAdjacentHTML('beforeend', footerHTML);

    // 5. Load footer_feedback.js dynamically
    const script = document.createElement('script');
    script.src = 'footer_feedback.js';
    document.body.appendChild(script);

})();