// EMPOWERING ENGINEERS UK - DYNAMIC FOOTER & DATA MANAGER
// Updated: 2-Column Layout, Split Navigation, Cleaned
(function() {
    const year = new Date().getFullYear();

    // Data Management Logic
    window.eeDataManager = {
        exportData: function() {
            const data = JSON.stringify(localStorage);
            const blob = new Blob([data], {type: "application/json"});
            const url = URL.createObjectURL(blob);
            const now = new Date();
            const timestamp = now.toISOString().replace(/T/, '_').replace(/:/g, '-').slice(0, 19);
            const a = document.createElement('a');
            a.href = url;
            a.download = `EmpoweringEngineers_Backup_${timestamp}.json`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
        },
        triggerImport: function() {
            document.getElementById('ee-import-input').click();
        },
        handleImport: function(input) {
            const file = input.files[0];
            if (!file) return;
            const reader = new FileReader();
            reader.onload = function(e) {
                try {
                    const data = JSON.parse(e.target.result);
                    if (confirm("⚠️ RESTORE WARNING:\n\nThis will overwrite your current browser data. Proceed?")) {
                        localStorage.clear();
                        Object.keys(data).forEach(k => localStorage.setItem(k, data[k]));
                        alert("✅ Data Restored. Reloading...");
                        location.reload();
                    }
                } catch (err) { alert("❌ Invalid Backup File. Please ensure you are using a .JSON file generated by this tool."); }
            };
            reader.readAsText(file);
        }
    };

    // Refined CSS - Ultra Compact
    const footerCSS = `
    <style>
        footer {
            margin-top: 30px;
            border-top: 1px solid var(--border-color);
            background: var(--dark-card);
            padding-top: 20px;
            padding-bottom: 10px;
            font-size: 0.8rem;
            color: var(--slate-grey);
            font-family: Arial, sans-serif;
        }
        
        /* NUCLEAR RESET: Force remove all dots/bullets */
        footer ul, footer li, footer ol {
            list-style: none !important;
            list-style-type: none !important;
            padding: 0 !important;
            margin: 0 !important;
            display: block !important;
        }
        footer li::before, footer li::after {
            content: none !important;
            display: none !important;
        }

        /* 2-COLUMN LAYOUT */
        .footer-content {
            max-width: 1000px;
            margin: 0 auto;
            padding: 0 20px;
            display: grid;
            grid-template-columns: 1fr 1fr; /* Nav | Data */
            gap: 40px;
            align-items: start;
            margin-bottom: 20px;
        }

        /* COLUMN HEADERS */
        .footer-col h5 {
            color: var(--terminal-green);
            text-transform: uppercase;
            font-size: 0.7rem;
            margin-bottom: 10px;
            border-bottom: 1px dashed #333;
            padding-bottom: 4px;
            letter-spacing: 0.5px;
        }

        /* NAVIGATION: 2 SUB-COLUMNS */
        .footer-links {
            display: grid;
            grid-template-columns: 1fr 1fr; /* 2 Sub-cols */
            gap: 6px 20px; /* Row Gap | Col Gap */
        }
        .footer-links a {
            text-decoration: none;
            color: var(--slate-grey);
            transition: color 0.2s;
            display: block;
            white-space: nowrap;
        }
        .footer-links a:hover { color: var(--terminal-green); }

        /* DATA SECTION */
        .data-note {
            font-size: 0.7rem;
            color: #666;
            margin: 0 0 8px 0;
            font-style: italic;
            line-height: 1.3;
        }
        .data-actions {
            display: flex;
            gap: 10px;
            align-items: center;
        }
        .dt-text-btn {
            background: none;
            border: 1px solid #444;
            border-radius: 3px;
            color: var(--slate-grey);
            cursor: pointer;
            font-family: inherit;
            font-size: 0.7rem;
            padding: 4px 8px;
            text-decoration: none;
            display: inline-block;
            transition: 0.2s;
        }
        .dt-text-btn:hover { border-color: var(--terminal-green); color: var(--terminal-green); }

        /* COPYRIGHT ROW */
        .footer-bottom {
            max-width: 1000px;
            margin: 0 auto;
            text-align: center;
            border-top: 1px solid rgba(255,255,255,0.05);
            padding-top: 10px;
            font-size: 0.7rem;
            opacity: 0.5;
        }

        /* MOBILE RESPONSIVENESS */
        @media (max-width: 600px) {
            .footer-content {
                display: flex;
                flex-direction: column;
                text-align: center;
                gap: 25px;
            }
            .footer-links {
                display: flex;
                flex-direction: column;
                gap: 8px;
            }
            .data-actions { justify-content: center; }
        }
    </style>
    `;

    const footerHTML = `
    ${footerCSS}
    <footer>
        <div class="footer-content">
            
            <div class="footer-col">
                <h5>Navigation</h5>
                <div class="footer-links">
                    <a href="https://www.empoweringengineers.uk/">Home</a>
                    <a href="about.html">About Us</a>
                    <a href="contact.html">Contact Us</a>
                    <a href="terms.html">Terms of Use</a>
                    <a href="privacy.html">Privacy Policy</a>
					<a href="sitemap.xml">Sitemap</a>
                </div>
            </div>

            <div class="footer-col">
                <h5>Data Control</h5>
                <div class="data-tools-compact">
                    <p class="data-note">
                        <strong>No Cloud Storage. We don't see your data.</strong><br>
                        Your data is stored locally and you can transfer it to another device.
                    </p>
                    <div class="data-actions">
                        <button class="dt-text-btn" onclick="window.eeDataManager.exportData()">&#11015; Save Backup</button>
                        <button class="dt-text-btn" onclick="window.eeDataManager.triggerImport()">&#8635; Restore Data</button>
                    </div>
                    <input type="file" id="ee-import-input" style="display:none" accept=".json" onchange="window.eeDataManager.handleImport(this)">
                </div>
            </div>

        </div>

        <div class="footer-bottom">
            &copy; ${year} Empowering Engineers UK. All rights reserved.
        </div>
    </footer>
    `;

    document.body.insertAdjacentHTML('beforeend', footerHTML);
    
    // Feedback Button
    const script = document.createElement('script');
    script.src = 'footer_feedback.js';
    document.body.appendChild(script);
})();